import type { Metadata } from "next";
import { SimplePage, Prose } from "@/components/layout/SimplePage";

export const metadata: Metadata = { title: "About us" };

export default function AboutPage() {
  return (
    <SimplePage
      eyebrow="About"
      title="We built the thing we kept rebuilding for clients."
      lead="LAMID ONE came out of consulting engagements that ended the same way: a good recommendation, a deck, and an organisation that could not reproduce the reasoning six months later."
    >
      <Prose>
        <h2>Why this exists</h2>
        <p>
          Advisory work has a structural problem. The most valuable part of an engagement is the
          model — the way the problem was framed, the factors that were weighted, the arithmetic
          that produced the number. That part leaves when the consultants do. What stays is a
          document describing a conclusion nobody can now re-derive.
        </p>
        <p>
          So the next time the question comes up, the organisation buys the discovery phase again.
          We did this to clients for years and eventually decided the model should stay with the
          people who paid for it.
        </p>

        <h2>What we believe</h2>
        <ul>
          <li>
            Show the arithmetic. If a number matters enough to decide on, it matters enough to be
            reproducible. Nothing in LAMID FINANCE is generated by a language model.
          </li>
          <li>
            Charge for outcomes. Agents are billed per completed result, so a failed run costs
            nothing. Any other arrangement puts the risk of bad output on the customer.
          </li>
          <li>
            Build capability, not dependency. LAMID LEARN certifies your own people. A platform
            engineered to remain permanently necessary is a retainer with a login screen.
          </li>
          <li>
            Publish what is not done. Our trust centre lists five things we have not certified,
            including SOC 2. Procurement finds out eventually; better from us.
          </li>
        </ul>

        <h2>Where we are</h2>
        <p>
          Early. The platform is built and the engines compute, but we do not yet have the outcome
          data to make the sort of percentage claims most software companies put on a homepage — so
          we have not made them. The stat tiles on this site refuse to render a figure we have not
          verified. That is a deliberate constraint in the code, not an oversight.
        </p>
      </Prose>
    </SimplePage>
  );
}
