import type { Metadata } from "next";
import { SimplePage, Prose } from "@/components/layout/SimplePage";
import { yearsOfOperation } from "@/content/brand";

export const metadata: Metadata = { title: "About us" };

/**
 * Sourced from LAMID Consulting's own corporate brochure — mission,
 * vision, core values, leadership and client list are quoted or
 * closely paraphrased from that document, not invented. The one thing
 * kept separate: the brochure's confidence about the consultancy
 * (35+ years, real engagements) is not extended to the SOFTWARE
 * platform, which genuinely is early — see "Where we are" below,
 * unchanged from the honest-state discipline the rest of this build
 * already applies to stat tiles and outcome claims.
 */
export default function AboutPage() {
  const years = yearsOfOperation();
  return (
    <SimplePage
      eyebrow="About"
      title={`${years}+ years of advisory work, rebuilt as software.`}
      lead="LAMID Consulting has run advisory engagements since 1988. LAMID ONE is that practice's own model — the way it frames a decision, weighs a factor, does the arithmetic — put into a platform clients keep, instead of a deck that leaves when the consultants do."
    >
      <Prose>
        <h2>Where this comes from</h2>
        <p>
          LAMID Consulting is a management consulting firm founded in 1988. Over more than three
          decades it has advised private-sector companies, international donors and government
          agencies, and built LAMID&apos;s Business Innovation Zone (BIZ) — an entrepreneurship
          and SME-advisory practice that has empowered over 3,000 SME clients and trained more
          than 5,000 professionals across government, the private sector and NGOs.
        </p>
        <p>
          BIZphere — the online marketplace where LAMID&apos;s SME clients met buyers and exchanged
          services — is the direct predecessor to LAMID MARKET, and the reason a version of that
          same idea now shows up as a scroll-triggered introduction on this site rather than a
          feature invented from scratch.
        </p>

        <h2>Mission and vision</h2>
        <p>
          <em>
            &ldquo;We improve our clients&apos; performance and achieve massive results by providing
            a million-dollar value job with an A+ effort, using innovation and technology.&rdquo;
          </em>
        </p>
        <p>
          The firm&apos;s stated goal is to produce thousands more world-class talents who can
          deliver exceptional value — the same capability-building goal LAMID LEARN exists to
          serve, for any team on this platform, anywhere.
        </p>

        <h2>What we believe</h2>
        <p>LAMID Consulting names eight core values. Each has a direct, checkable equivalent in how this platform actually works:</p>
        <ul>
          <li>
            <strong>Innovation &amp; Results Driven</strong> — show the arithmetic. If a number
            matters enough to decide on, it matters enough to be reproducible. Nothing in LAMID
            FINANCE is generated by a language model.
          </li>
          <li>
            <strong>Client Value Creation</strong> — charge for outcomes. Agents are billed per
            completed result, so a failed run costs nothing.
          </li>
          <li>
            <strong>Learning Advantage</strong> — build capability, not dependency. LAMID LEARN
            certifies your own people rather than keeping the knowledge with us.
          </li>
          <li>
            <strong>Authenticity &amp; Simplicity</strong> — publish what is not done. Our trust
            centre lists what we have not yet certified, including SOC 2. Procurement finds out
            eventually; better from us.
          </li>
          <li>
            <strong>Integrity, Partnership, Seamless Service, Timely Solution</strong> — the
            remaining four are less a feature than a standard the rest of this build is held to.
          </li>
        </ul>

        <h2>Leadership</h2>
        <p>
          Maureen Akintayo, MPA, LEAD Fellow, is LAMID Consulting&apos;s Lead Consultant and its
          frontline advisor on human capital development and BIZ. She was the first UNDP-certified
          woman for SME development (1992), a Lead Consultant on the UNDP flagship programme
          Enterprise Africa, and Regional Director of the Leadership for Environment and
          Development (LEAD) Programme, a Rockefeller Foundation initiative now active in over 20
          countries.
        </p>

        <h2>Where we are</h2>
        <p>
          Early. The platform is built and the engines compute, but we do not yet have the outcome
          data to make the sort of percentage claims most software companies put on a homepage — so
          we have not made them. The stat tiles on this site refuse to render a figure we have not
          verified. That is a deliberate constraint in the code, not an oversight — the same
          discipline the firm behind it has applied to client work for {years}+ years.
        </p>
      </Prose>
    </SimplePage>
  );
}
