/**
 * USE CASES — the verb tree.
 *
 * Template (teardown §7.2):
 *   H1     transformation, not feature: `Turn [pain] into [state]`
 *   H2     the problem, named
 *   H2     a numbered 3–4 step framework — the framework IS the content
 *   H2     what makes our approach different
 *   H2     proof
 *   FAQ
 *   close  imperative
 *   + lateral navigation to sibling use cases
 *
 * NO PRICING on a use-case page. These sell the problem being solved;
 * introducing price mid-argument kills the argument. Price is one click
 * away in the nav.
 */

import type { FaqItem } from "@/components/sections/Faq";
import type { SuiteId } from "./suites";
import type { Engine } from "./aios";

export type UseCase = {
  slug: string;
  /** Nav label — short verb phrase. */
  nav: string;
  headline: string;
  subhead: string;
  /**
   * Which of the four engines owns this use case.
   *
   * Structural, not copy. It resolves the value shown in the hero
   * (ENGINES[].value) and the module content the page pulls — so these
   * pages state the same four-engine structure as the homepage instead
   * of flattening `suites` back into a list of peers.
   *
   * `suites` still records every suite the work actually touches, which
   * is frequently more than one engine's worth. The engine named here
   * is the one that owns the outcome.
   */
  engine: Engine["id"];
  /**
   * Title of the matching entry in the brand document's USE_CASES, when
   * there is one. Five of the nine have a document equivalent; the rest
   * predate it and are left without rather than invented into one.
   */
  docUseCase?: string;
  problem: { title: string; body: string; symptoms: string[] };
  framework: { title: string; steps: { n: string; title: string; body: string }[] };
  different: { title: string; body: string; points: string[] };
  suites: SuiteId[];
  faq: FaqItem[];
  closing: { title: string; body: string };
};

export const USE_CASES: UseCase[] = [
  {
    slug: "diagnose",
    engine: "core",
    docUseCase: "Leadership Decision Intelligence",
    nav: "Diagnose the organisation",
    headline: "Turn a vague sense that something is wrong into a specific answer.",
    subhead:
      "Before you spend on a transformation programme, find out what is actually broken — scored on your own data, not on an interview round.",
    problem: {
      title: "Why most diagnostics tell you what you already suspected",
      body:
        "A traditional diagnostic is a round of interviews summarised into themes. It reflects who was in the room and how articulate they were. Six weeks and a six-figure fee later you have a deck that confirms the loudest opinion.",
      symptoms: [
        "Every function has a different account of what the problem is",
        "The last strategy review produced actions nobody can now find",
        "You are being asked to fund a fix before anyone has isolated the cause",
      ],
    },
    framework: {
      title: "How a LAMID diagnostic runs",
      steps: [
        { n: "01", title: "Answer the structured intake", body: "A typed input spec per dimension — not a blank questionnaire. Ten minutes for a single function, longer for a full organisation." },
        { n: "02", title: "The engines compute a score", body: "194 CORE engines assess decision quality, cadence, alignment and governance against your inputs. The arithmetic is shown." },
        { n: "03", title: "Read the gap, not the theme", body: "You get scored dimensions with the specific engines that flagged them, so 'communication is poor' becomes a named cadence drift between two teams." },
        { n: "04", title: "Act, or source someone who can", body: "Each finding links to the engine that fixes it, or becomes a scoped brief you can send to a vetted expert." },
      ],
    },
    different: {
      title: "What makes this different",
      body: "The diagnostic is not a report. It is a computed baseline you can re-run, so improvement is measurable rather than asserted.",
      points: [
        "Re-runnable — the second diagnostic is a comparison, not a restart",
        "Every score traces to the engine and the inputs that produced it",
        "Findings become briefs, so the fix does not need a new procurement",
        "Costs 40 points, not a six-week engagement",
      ],
    },
    suites: ["core", "market"],
    faq: [
      { q: "How long does an organisational diagnostic take?", a: "A single function takes about ten minutes of structured input. A full organisational read across strategy, cadence, talent and finance takes a few hours, usually spread across the people who hold each area." },
      { q: "How much does a business diagnostic cost?", a: "40 LAMID Points. A new free account is granted exactly that — enough for one full diagnostic, at no cost and with no card. Further runs are bought as points; there is no consulting fee attached to any of them." },
      { q: "Is the diagnostic generated by AI?", a: "The scoring is arithmetic, computed by the engines from your inputs. The Diagnostic Agent writes the narrative around the scores and explains what they mean — it does not invent the numbers." },
      { q: "How is this different from a consulting diagnostic?", a: "A consulting diagnostic is a point-in-time interpretation that leaves with the consultant. This is a computed baseline that stays, can be re-run, and shows its working — so you can prove whether the fix worked." },
    ],
    closing: { title: "Find out what is actually wrong.", body: "The first diagnostic is free and takes ten minutes." },
  },
  {
    slug: "align-strategy",
    engine: "core",
    nav: "Align strategy and execution",
    headline: "Turn a strategy nobody follows into one the work actually reflects.",
    subhead:
      "Hold the plan, the decisions and the delivery against each other continuously — so drift is visible in weeks rather than at the annual review.",
    problem: {
      title: "Why the plan and the work drift apart",
      body:
        "Strategy lives in a deck, decisions live in meetings, and delivery lives in a project tool. Nothing connects them, so the first time anyone notices the divergence is when the results miss.",
      symptoms: [
        "Teams are busy but the strategic priorities have not moved",
        "Nobody can say which decisions the current plan actually depends on",
        "The quarterly review is the first time drift becomes visible",
      ],
    },
    framework: {
      title: "Your path to alignment",
      steps: [
        { n: "01", title: "Map the strategic priorities", body: "Weight them against each other, so trade-offs are explicit rather than implied." },
        { n: "02", title: "Attach the decisions", body: "Every priority carries the decisions it depends on, with owners and current state." },
        { n: "03", title: "Measure against delivery cadence", body: "Cadence engines compare the tempo teams actually run at with the tempo the plan assumes." },
        { n: "04", title: "Get told when it drifts", body: "Drift alerts fire when a team's pace or focus moves away from the priority it serves." },
      ],
    },
    different: {
      title: "What makes this different",
      body: "Most alignment tools ask people to self-report status. These engines read the cadence of actual delivery, so alignment is measured rather than declared.",
      points: [
        "Drift is detected from delivery tempo, not from a status field",
        "Trade-offs between priorities are explicit and weighted",
        "Every priority traces to the decisions it depends on",
        "The record survives a change of leadership",
      ],
    },
    suites: ["core"],
    faq: [
      { q: "What is strategic alignment software?", a: "It holds strategic priorities, the decisions that support them, and the delivery work that implements them in one connected structure — so divergence between intent and execution becomes measurable." },
      { q: "How quickly does drift show up?", a: "Cadence engines read delivery tempo continuously, so a team drifting from the pace a priority requires surfaces in weeks rather than at the next quarterly review." },
      { q: "Do teams have to change how they work?", a: "No. The engines read the rhythm of work already happening. There is no new status ritual to maintain." },
      { q: "How is this different from an OKR tool?", a: "OKR tools record what people say the status is. These engines measure the cadence of delivery itself, and hold the decision rationale behind each priority — so when a goal slips you can trace which decision caused it." },
    ],
    closing: { title: "Stop finding out at the quarterly review.", body: "Map one priority and see where it is drifting." },
  },
  {
    slug: "fix-cadence",
    engine: "core",
    docUseCase: "Operational Performance Improvement",
    nav: "Fix the execution cadence",
    headline: "Turn inconsistent delivery into a rhythm you can plan against.",
    subhead:
      "Most plans fail on tempo, not on strategy. Find the pace each team actually runs at, and where those paces conflict.",
    problem: {
      title: "Why delivery feels unpredictable",
      body:
        "Different teams run at different natural tempos. When those tempos are not visible, handoffs land at the wrong time, work queues invisibly, and the plan assumes a pace nobody actually holds.",
      symptoms: [
        "Delivery estimates are consistently optimistic in the same direction",
        "Work waits on another team more often than it is worked on",
        "Nobody can say what a realistic pace looks like for this organisation",
      ],
    },
    framework: {
      title: "Your path to a stable cadence",
      steps: [
        { n: "01", title: "Map the real cadence", body: "30 cadence engines read the tempo each team actually delivers at — not the one in the plan." },
        { n: "02", title: "Find the conflicts", body: "Cross-team cadence fit shows where one team's rhythm systematically strands another's." },
        { n: "03", title: "Balance the load", body: "Workload balance monitoring finds the teams absorbing variance for everyone else." },
        { n: "04", title: "Hold the new rhythm", body: "Stability scoring and drift alerts tell you when it slips, before it compounds." },
      ],
    },
    different: {
      title: "What makes this different",
      body: "Cadence is measured from delivery behaviour rather than from sprint ceremonies, so it works whatever methodology each team uses.",
      points: [
        "Methodology-agnostic — works across agile, stage-gate and ad hoc teams",
        "Detects volatility and tells you when a metric is too noisy to call a trend",
        "Surfaces the team carrying everyone else's variance",
        "Alerts on drift rather than reporting it a quarter later",
      ],
    },
    suites: ["core"],
    faq: [
      { q: "What is operating cadence?", a: "The recurring rhythm at which an organisation actually plans, decides and delivers. It is distinct from the process a team says it follows — cadence is the tempo the work genuinely moves at." },
      { q: "Does this work if teams use different methodologies?", a: "Yes. Cadence is read from delivery behaviour rather than from ceremonies, so agile, stage-gate and unstructured teams can be compared on the same basis." },
      { q: "How many periods of data does it need?", a: "Six periods gives a reliable trend and swing reading. With fewer, the engines will tell you the signal is too volatile to call rather than reporting a false trend." },
      { q: "How is this different from a project management tool?", a: "A project tool tracks whether tasks are done. Cadence engines measure the rhythm across teams and detect when one team's tempo is systematically stranding another's — which is invisible inside any single project board." },
    ],
    closing: { title: "Find the tempo you actually run at.", body: "The operating rhythm scorecard is free and takes five minutes." },
  },
  {
    slug: "model-financials",
    engine: "finance",
    docUseCase: "Financial Foresight & Performance Optimisation",
    nav: "Model the financials",
    headline: "Turn a spreadsheet nobody trusts into numbers you can defend.",
    subhead:
      "Costed budgets, forecasts and margin models computed from your figures — with the arithmetic shown and exportable, never generated by a model.",
    problem: {
      title: "Why the numbers stop being trusted",
      body:
        "Spreadsheets do arithmetic well and everything else badly. There is no audit trail, three versions are in circulation, and nobody can say which assumptions produced the figure in the board pack.",
      symptoms: [
        "More than one version of the budget is in active use",
        "Nobody can reproduce how last quarter's forecast was built",
        "Assumptions are buried in cells rather than stated",
      ],
    },
    framework: {
      title: "Your path to defensible numbers",
      steps: [
        { n: "01", title: "Enter your figures", body: "Structured inputs per model — costs, rates, volumes, timelines — with validation on each." },
        { n: "02", title: "Watch it compute", body: "Overhead, contingency and tax recalculate as you edit. Every step of the arithmetic is visible." },
        { n: "03", title: "Track against actuals", body: "Every line compares to what you really spent, period by period." },
        { n: "04", title: "Export the working", body: "The board pack ships with the reasoning attached, not just the answer." },
      ],
    },
    different: {
      title: "What makes this different",
      body: "No figure on a LAMID FINANCE screen is produced by a language model. Every number is computed arithmetically from inputs you entered, and you can export the calculation.",
      points: [
        "Zero model-generated figures — arithmetic is shown and exportable",
        "One version, permissioned, with a full change history",
        "Assumptions are named fields rather than buried cells",
        "Recalculates continuously as the business moves",
      ],
    },
    suites: ["finance"],
    faq: [
      { q: "What is financial modelling software?", a: "It computes budgets, forecasts, cost structure and valuation from structured inputs, keeping the assumptions explicit and the calculation reproducible — which a spreadsheet does not." },
      { q: "Does AI generate the financial figures?", a: "No. Every figure is arithmetic computed from your inputs, and the working is exportable. AI agents can explain a result or draft commentary around it, but they never produce the numbers." },
      { q: "Can I export to Excel?", a: "Yes. Every engine result exports as CSV on every tier, and the export includes the working — the calculation steps behind each figure, not only the final numbers. PDF export of a model is not built yet." },
      { q: "How is this different from a spreadsheet?", a: "Same arithmetic, but versioned, permissioned, validated on input, and attached to the decision and engagement the number was for. A spreadsheet forgets why the figure existed; this does not." },
    ],
    closing: { title: "Build one costed budget.", body: "The budget estimator is free — bring last quarter's numbers." },
  },
  {
    slug: "find-growth",
    engine: "grow",
    docUseCase: "Transformation Acceleration",
    nav: "Find where growth is leaking",
    headline: "Turn a growth plan built on hope into one built on signal.",
    subhead:
      "See where growth compounds and where it drains — and check the plan against the capacity you actually have.",
    problem: {
      title: "Why growth plans miss",
      body:
        "Growth targets are usually set top-down and resourced afterwards. By the time the gap between ambition and capacity is visible, two quarters of spend have gone into a plan that was never deliverable.",
      symptoms: [
        "The plan assumes hiring or capability that has not been secured",
        "Market shifts are noticed through results rather than in advance",
        "Nobody can say which growth lever is actually working",
      ],
    },
    framework: {
      title: "Your path to a resourced growth plan",
      steps: [
        { n: "01", title: "Read the market", body: "Market intelligence and opportunity signals tracked continuously rather than commissioned annually." },
        { n: "02", title: "Score your maturity", body: "Digital maturity assessed against where you need to be, not against an industry average." },
        { n: "03", title: "Check against capacity", body: "The growth planner ties ambition to the people, cash and cadence you actually have." },
        { n: "04", title: "Report without rebuilding", body: "Board reporting is generated from the live data rather than assembled the week before." },
      ],
    },
    different: {
      title: "What makes this different",
      body: "Growth plans here are checked against the TALENT and FINANCE engines, so an unresourceable plan is flagged before it is approved rather than after it fails.",
      points: [
        "Ambition checked against real workforce and cash capacity",
        "Signals tracked continuously, not commissioned per cycle",
        "Board reporting generated from live data",
        "Modernisation routes compared with what each actually requires",
      ],
    },
    suites: ["grow", "finance", "talent"],
    faq: [
      { q: "What is growth intelligence software?", a: "It combines continuous market signal with an internal read on capacity, so growth planning is constrained by what the organisation can actually deliver rather than by ambition alone." },
      { q: "Where does the market data come from?", a: "From your own performance data plus configured external signal sources. The engines compute the read; they do not resell a generic industry report." },
      { q: "Can it tell me which growth lever is working?", a: "Yes — that is what the opportunity signal and cadence engines together are for: separating the levers that compound from the ones absorbing effort without return." },
      { q: "How is this different from a market research report?", a: "A report describes what happened and ends. These engines connect the signal to a plan, check the plan against your capacity, and keep updating as both move." },
    ],
    closing: { title: "Find the leak before the next quarter.", body: "Start with a growth diagnostic on one market." },
  },
  {
    slug: "get-paid",
    engine: "finance",
    nav: "Get paid faster",
    headline: "Turn a proposal, a contract and an invoice into one record.",
    subhead:
      "Scope from the diagnostic, sign in place, run milestones through escrow, and release payment on approval — without three systems disagreeing.",
    problem: {
      title: "Why cash arrives later than the work finishes",
      body:
        "The proposal lives in a document tool, the contract in someone's email, the delivery in a project board and the invoice in accounting software. Every handoff between them is a delay, and every delay is working capital.",
      symptoms: [
        "Invoices go out days or weeks after the work is accepted",
        "Scope changes are agreed verbally and reconciled later",
        "Nobody can see the full commercial picture of an engagement in one place",
      ],
    },
    framework: {
      title: "Your path from quote to cash",
      steps: [
        { n: "01", title: "Scope it from what you know", body: "The Proposal Agent drafts a scoped, costed proposal from diagnostic output rather than a blank page." },
        { n: "02", title: "Sign in place", body: "Quotes and e-signature on the same record, so the agreed scope is the scope that gets delivered." },
        { n: "03", title: "Deliver against milestones", body: "The Milestone Agent breaks the scope into deliverables with release conditions attached." },
        { n: "04", title: "Release on approval", body: "Escrow releases when you approve, and invoicing reflects the real contract including mid-flight changes." },
      ],
    },
    different: {
      title: "What makes this different",
      body: "The commercial record and the delivery record are the same record, so a scope change updates the invoice rather than requiring a reconciliation.",
      points: [
        "One record from proposal through to payment",
        "Escrow-backed milestones with approval-gated release",
        "Invoices reflect mid-contract changes automatically",
        "Nine currencies including naira, cedi, shilling, rand and dirham",
      ],
    },
    suites: ["desk", "market"],
    faq: [
      { q: "What is quote-to-cash software?", a: "It connects the commercial lifecycle — proposal, quote, signature, contract, delivery milestones, invoice and payment — so each step inherits the last rather than being re-entered." },
      { q: "How do milestones work?", a: "Work is agreed as milestones. A milestone clears when you approve the deliverable, or automatically if you raise no objection inside the review window; a dispute stops that and the Dispute Agent assembles evidence from both sides first. Fund holds are not built yet — approval marks a milestone cleared for payment rather than moving money — and that is listed on the trust centre." },
      { q: "Which payment methods are supported?", a: "Card and subscription payments through Stripe, and local collection and payout rails through Paystack, with webhook reconciliation. Checkout supports nine currencies." },
      { q: "How is this different from using separate tools?", a: "Separate tools each hold part of the truth and disagree at the edges. Here the proposal, the contract, the milestone and the invoice are views of one record, so a change in one is a change in all." },
    ],
    closing: { title: "Shorten the gap between done and paid.", body: "Set up one engagement end to end and see the difference." },
  },
  {
    slug: "build-bench",
    engine: "talent",
    docUseCase: "Workforce Capability Mapping & Skill Acceleration",
    nav: "Build the talent bench",
    headline: "Turn a succession plan in a spreadsheet into cover you can rely on.",
    subhead:
      "Know which roles have no ready successor, which teams are stretched, and who is at risk — before the resignation arrives.",
    problem: {
      title: "Why succession planning fails quietly",
      body:
        "Succession is usually an annual exercise producing a grid that is stale within a quarter. Nobody re-runs it, so the first signal that cover was thin is a resignation nobody had planned for.",
      symptoms: [
        "The succession grid was last updated more than two quarters ago",
        "Critical-role cover is asserted rather than assessed",
        "Flight risk is discovered at the exit interview",
      ],
    },
    framework: {
      title: "Your path to real bench strength",
      steps: [
        { n: "01", title: "Score capability against roles you need now", body: "Not against last year's org chart — against the roles the current plan requires." },
        { n: "02", title: "Assess cover per critical role", body: "Bench strength engines score depth for every role you cannot afford to leave open." },
        { n: "03", title: "Read risk from behaviour", body: "Engagement signals and load monitoring surface risk before it becomes attrition." },
        { n: "04", title: "Close the gap deliberately", body: "Career pathing and targeted leadership development aimed at the measured gap, with LEARN certification behind it." },
      ],
    },
    different: {
      title: "What makes this different",
      body: "Capability is scored on 40+ signals and re-run continuously, so bench strength is a live reading rather than an annual snapshot.",
      points: [
        "Matched on 40+ signals, not on CVs and impressions",
        "Continuous rather than annual",
        "People risk connected to business risk, not held separately",
        "Development targeted at the measured gap and certified in LEARN",
      ],
    },
    suites: ["talent", "learn"],
    faq: [
      { q: "What is people intelligence software?", a: "It holds workforce capability, risk, succession and engagement as continuously-scored data, so people decisions carry the same standard of evidence as financial ones." },
      { q: "How is flight risk assessed?", a: "From behavioural and workload signals rather than from a survey alone — engagement signal engines read patterns in how people are actually working, including who is absorbing unsustainable load." },
      { q: "Does this replace our HR system?", a: "No. An HRIS records who works here and what they are paid. This reads capability, risk and readiness on top of that, and the two are complementary." },
      { q: "How is this different from an annual engagement survey?", a: "A survey is a point-in-time self-report with a response-rate problem. These engines run continuously on behavioural signal, so a team becoming stretched shows up in weeks rather than at the next survey cycle." },
    ],
    closing: { title: "Find out where your cover is thin.", body: "The bench strength snapshot is free with an account." },
  },
  {
    slug: "source-experts",
    engine: "talent",
    nav: "Source specialist expertise",
    headline: "Turn a six-week procurement into a shortlist this week.",
    subhead:
      "Matched experts on 40+ signals, milestone escrow so payment only releases on approved work, and the engagement record attached to the diagnostic that started it.",
    problem: {
      title: "Why sourcing specialist help is slow",
      body:
        "You either run a procurement process that takes longer than the problem allows, or you call someone you already know and hope the fit is right. Neither approach produces evidence that this is the right person for this problem.",
      symptoms: [
        "Specialist capability is sourced through personal networks by default",
        "Procurement takes longer than the window the problem allows",
        "There is no record of why a particular provider was chosen",
      ],
    },
    framework: {
      title: "Your path to the right expert",
      steps: [
        { n: "01", title: "Turn the finding into a brief", body: "A diagnostic finding becomes a scoped brief without re-typing the context." },
        { n: "02", title: "Get a matched shortlist", body: "The Matching Agent scores on industry, challenge type, budget, timeline and working style — 30 points, not a procurement cycle." },
        { n: "03", title: "Engage with escrow", body: "Milestones agreed up front, funds held before work starts, released only on your approval." },
        { n: "04", title: "Keep the record", body: "Deliverables, decisions and outcomes stay attached to the engagement for the next time." },
      ],
    },
    different: {
      title: "What makes this different",
      body: "Engagement counts are published on every profile even when they are low — publishing the small numbers is what makes the large ones believable.",
      points: [
        "Matched on discipline and evidence, not on keyword search",
        "Engagement counts published even when low",
        "Verification and credentials checkable, and selectively awarded",
        "Escrow with a structured dispute path that does not need a lawyer",
      ],
    },
    suites: ["market", "desk"],
    faq: [
      { q: "How does expert matching work?", a: "Semantic matching scores your brief against expert profiles on industry, challenge type, budget, timeline and working style, returning a ranked shortlist rather than a directory page. A match costs 30 LAMID Points." },
      { q: "How are experts vetted?", a: "Through identity and credential verification with an operator review queue, plus engagement history and reviews accumulated on the platform. Verification badges are awarded selectively — a badge everyone holds is not a badge." },
      { q: "What protects me if the work is not delivered?", a: "Funds sit in escrow against each milestone and release only when you approve the deliverable. Disputes are assembled with evidence from both sides before any decision." },
      { q: "How is this different from a freelance marketplace?", a: "Freelance platforms stop at introduction and take a percentage indefinitely. Here the engagement carries your diagnostic context, runs on escrow-backed milestones, and the delivery record stays attached to the problem it was solving." },
    ],
    closing: { title: "Post a brief and see who comes back.", body: "Posting is free on every plan." },
  },
  {
    slug: "certify-teams",
    engine: "talent",
    nav: "Certify your teams",
    headline: "Turn a dependency on consultants into capability you own.",
    subhead:
      "Structured programmes, live events, AI tutoring and assessed certification — taught on the system your organisation actually runs.",
    problem: {
      title: "Why training does not transfer",
      body:
        "Generic courses teach a topic in the abstract and are assessed by a quiz. People complete them, nothing changes, and the organisation stays dependent on the outside expertise it was trying to replace.",
      symptoms: [
        "Course completion is high and behaviour change is not visible",
        "The same external help is bought for the same problem each year",
        "Capability is claimed but cannot be evidenced",
      ],
    },
    framework: {
      title: "Your path to owned capability",
      steps: [
        { n: "01", title: "Baseline the gap", body: "TALENT capability engines establish where the organisation actually is before anyone enrols." },
        { n: "02", title: "Run the programme", body: "Structured paths and live cohort sessions in LAMID Learning, with an AI tutor answering in context." },
        { n: "03", title: "Assess against real work", body: "Certification is assessed on work done in the platform, not on a multiple-choice test." },
        { n: "04", title: "Re-measure", body: "Re-run the capability baseline and report the uplift as a number rather than a completion rate." },
      ],
    },
    different: {
      title: "What makes this different",
      body: "Learning is built on the disciplines the platform runs on and assessed against real platform work, so uplift shows in the TALENT baseline rather than only on a certificate.",
      points: [
        "Taught on the system you actually use",
        "Assessed against real work, not a quiz",
        "Uplift measured against the TALENT capability baseline",
        "Credentials also surface on marketplace expert profiles",
      ],
    },
    suites: ["learn", "talent"],
    faq: [
      { q: "What is a learning management system?", a: "Software that delivers structured programmes, tracks progress, runs assessment and issues credentials. LAMID Learning is multi-tenant, so each organisation gets its own learning workspace." },
      { q: "Does LAMID Learning open separately?", a: "Yes, it runs as its own application and opens in a new tab. Seats, certification records and completion reporting sync back automatically, so uplift appears against your TALENT baseline." },
      { q: "How is certification assessed?", a: "Against work done in the platform rather than a multiple-choice test — which is why a LAMID credential means something checkable to a client or an employer." },
      { q: "How is this different from a generic course library?", a: "A generic library teaches topics in the abstract and cannot tell you whether capability changed. This is taught on your own operating method, assessed on your own work, and measured against a capability baseline you can re-run." },
    ],
    closing: { title: "Stop renting the same capability every year.", body: "The first learning path costs nothing." },
  },
];

export const getUseCase = (slug: string) => USE_CASES.find((u) => u.slug === slug);
